### ISSUE TITLE
Disconnect problem | DotNetty.Codecs.DecoderException

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#165] opened 2017-05-01 20:46 UTC
My friend disconnect from server after like ~1-5 minute game. 
What problem?

Error every time same (in every mode).
It's be in room/playing room. We stay in lobby room, no play and here her connection dropped to lobby. When play - relay connection dropped client (client crash).
I host or he - it does not matter.

For local network (2 clients from 1 pc or 2 clients from same internet with 2 pc) - work normal. 
But sometimes this problem appear in local connection too.

UPD: See if people nothing do (no many kills, only run, jump) - problem can no appear. 
I no crash or disconnect every time. Only another people (of course if i no play from 2 accounts in same time from 1 PC, but dropped only 1 client).

```
2017-05-01 20:37:07.5638|INFO|GameServer:249||Saving players... 
2017-05-01 20:37:07.6838|INFO|GameServer:267||Saving players completed 
2017-05-01 20:37:57.0997|ERROR|RelayServer:66| [qwe123<7>-User]| 
DotNetty.Codecs.DecoderException: An exception of type "DotNetty.Codecs.DecoderException". ---> System.IndexOutOfRangeException: index: 80 (expected: range(0, 80)
   in DotNetty.Buffers.AbstractByteBuffer.CheckIndex(Int32 index)
   in DotNetty.Buffers.AbstractByteBuffer.GetByte(Int32 index)
   in DotNetty.Buffers.SwappedByteBuffer.GetByte(Int32 index)
   in ProudNet.Codecs.ProudFrameDecoder.GetUnadjustedFrameLength(IByteBuffer buffer, Int32 offset, Int32 length, ByteOrder order) в E:\s4\mygits1\src\ProudNet\Codecs\ProudFrameDecoder.cs:line 20
   in BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input)
   in BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   in DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   --- End trace of the internal exception stack ---
   in DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   in DotNetty.Codecs.ByteToMessageDecoder.ChannelRead(IChannelHandlerContext context, Object message)
   in DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)
2017-05-01 20:37:57.1227|ERROR|RelayServer:66|| 
DotNetty.Codecs.DecoderException: An exception of type "DotNetty.Codecs.DecoderException". ---> System.IndexOutOfRangeException: index: 80 (expected: range(0, 80)
   in DotNetty.Buffers.AbstractByteBuffer.CheckIndex(Int32 index)
   in DotNetty.Buffers.AbstractByteBuffer.GetByte(Int32 index)
   in DotNetty.Buffers.SwappedByteBuffer.GetByte(Int32 index)
   in ProudNet.Codecs.ProudFrameDecoder.GetUnadjustedFrameLength(IByteBuffer buffer, Int32 offset, Int32 length, ByteOrder order) в E:\s4\mygits1\src\ProudNet\Codecs\ProudFrameDecoder.cs:line 20
   in BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input)
   in BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   in DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   --- End trace of the internal exception stack ---
   in DotNetty.Codecs.ByteToMessageDecoder.ChannelInactive(IChannelHandlerContext ctx)
   in DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelInactive()
2017-05-01 20:37:57.1367|DEBUG|GameServer:187| [qwe123<7>-User]|Disconnected 
2017-05-01 20:38:06.2362|DEBUG|Player:162| [bioaleks<2>-Administrator]|Gained 73 exp 
2017-05-01 20:38:07.5913|INFO|GameServer:249||Saving players... 
2017-05-01 20:38:07.5913|INFO|GameServer:267||Saving players completed 
```

Client disconnect message: "The connection with Relay server has been terminated".
Click "OK" = client crash (no server).

**Comment by huenato** [comment] 2017-05-21 20:02
Seems to crash during a game.
<img src="https://puu.sh/vXhs8/ef57465fe7.png"/>

**Comment by wtfblub** [comment] 2017-09-11 16:29
Duplicate of #155

**Closed by wtfblub** 2017-09-11 16:29 UTC
Labels: Bug
