### ISSUE TITLE
Bug Report - Crash after a while of minutes

### ISSUE THREAD

**Issue by Tpk86** [wtfblub/NetspherePirates#52] opened 2016-08-20 19:43 UTC
Hi guys, similar problem here.
Ports are open for me and settings are right.
Tcp : 28002, 28003, 28004, 28005
Udp : 22000

I' m the hoster but after a while i crash and get "Failed connection to the relay server".
This happens only if the match is started.

Not sure but i think the problem is the sentry:
Network.Message.P2P.SentryGunSpawnMessageSerializer.Deserialize(
BinaryReader )

The error i get in console is that:

`
[RelayServer->OnError:94]
System.IO.EndOfStreamException: Impossibile leggere oltre la fine del flusso.
   in System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   in System.IO.BinaryReader.ReadInt16()
   in Netsphere.Network.NetsphereExtensions.ReadCompressedFloat(BinaryReader r)
in C:\projects\netspherepirates\src\Netsphere.Network\Extensions.cs:riga 60
   in Netsphere.Network.Message.P2P.SentryGunSpawnMessageSerializer.Deserialize(
BinaryReader )
   in BlubLib.Serialization.Serializer.Deserialize[T](BinaryReader reader)
   in BlubLib.Serialization.Serializer.Deserialize(BinaryReader reader, Type typ
e)
   in Netsphere.Network.Message.P2P.P2PMapper.GetMessage(Byte[] data) in C:\proj
ects\netspherepirates\src\Netsphere.Network\Message\P2P\P2PMapper.cs:riga 76
   in Netsphere.Network.Services.RelayService.Packet(IService service, RelaySess
ion session, PacketMessage message, MessageReceivedEventArgs e) in C:\projects\n
etspherepirates\src\Game\Network\Services\RelayService.cs:riga 20
   in RelayService.Packet(IMessageHandler , IService , MessageReceivedEventArgs
)
   in BlubLib.Network.Pipes.MessageHandler.BlubLib.Network.Pipes.IMessageHandler
.OnMessageReceived(IService service, MessageReceivedEventArgs e)
   in BlubLib.Network.Pipes.MessageHandlerPipe.OnMessageReceived(MessageReceived
EventArgs e)
   in BlubLib.Network.Pipes.FirewallPipe.OnMessageReceived(MessageReceivedEventA
rgs e)
   in BlubLib.Network.Pipe.OnMessageReceived(MessageReceivedEventArgs e)
   in Netsphere.Network.NetspherePipe.OnMessageReceived(MessageReceivedEventArgs
 e) in C:\projects\netspherepirates\src\Netsphere.Network\NetspherePipe.cs:riga
41
   in BlubLib.Network.Pipe.OnMessageReceived(MessageReceivedEventArgs e)
   in ProudNet.ProudPipe.NextOnMessageReceived(MessageReceivedEventArgs e) in C:
\projects\netspherepirates\src\ProudNet\ProudPipe.cs:riga 116
   in ProudNet.Services.ProudCoreService.RmiMessage(ProudSession session, RmiMes
sage message, MessageReceivedEventArgs e) in C:\projects\netspherepirates\src\Pr
oudNet\Services\ProudCoreService.cs:riga 57
   in ProudCoreService.RmiMessage(IMessageHandler , IService , MessageReceivedEv
entArgs )
   in BlubLib.Network.Pipes.MessageHandler.BlubLib.Network.Pipes.IMessageHandler
.OnMessageReceived(IService service, MessageReceivedEventArgs e)
   in ProudNet.ProudPipe.OnMessageReceived(MessageReceivedEventArgs e) in C:\pro
jects\netspherepirates\src\ProudNet\ProudPipe.cs:riga 94
   in ProudNet.Services.ProudCoreServerService.ReliableRelayHandler(ProudSession
 session, ReliableRelay1Message message, MessageReceivedEventArgs e) in C:\proje
cts\netspherepirates\src\ProudNet\Services\ProudCoreServerService.cs:riga 251
   in ProudCoreServerService.ReliableRelayHandler(IMessageHandler , IService , M
essageReceivedEventArgs )
   in BlubLib.Network.Pipes.MessageHandler.BlubLib.Network.Pipes.IMessageHandler
.OnMessageReceived(IService service, MessageReceivedEventArgs e)
   in ProudNet.ProudPipe.OnMessageReceived(MessageReceivedEventArgs e) in C:\pro
jects\netspherepirates\src\ProudNet\ProudPipe.cs:riga 94
   in BlubLib.Network.Pipes.ProtocolPipe.OnMessageReceived(MessageReceivedEventA
rgs e)
   in BlubLib.Network.Pipe.OnMessageReceived(MessageReceivedEventArgs e)
   in BlubLib.Network.Pipeline.OnMessageReceived(MessageReceivedEventArgs e)
   in BlubLib.Network.Transport.Sockets.TcpTransport.<ProcessReceive>d__27.MoveN
ext()
`

**Comment by wtfblub** [comment] 2016-08-20 20:09
Duplicate of #11

**Closed by wtfblub** 2016-08-20 20:09 UTC
Labels: Invalid-Duplicate
